version: "3"
services:
  nginx:
    image: nginx:alpine
    restart: always
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www/html/back
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./conf/nginx/ssl:/etc/nginx/ssl/
    depends_on:
      - php-fpm
      - db
    networks:
      - app-network

  php-fpm:
    build:
      context: .
      dockerfile: ./conf/php-fpm/Dockerfile
    restart: always
    tty: true
    volumes:
      - ./app:/var/www/html/back
      - ./conf/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - app-network

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_LOGIN==${DB_ROOT}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '3306:3306'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge